"$schema" = "https://starship.rs/config-schema.json"

format = """
$username\
$hostname\
$directory\
$kubernetes\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$nodejs\
$line_break\
$character"""

add_newline = true
palette = "cendre"

# cendre palette for Starship · hard
# https://github.com/Aejkatappaja/cendre
[palettes.cendre]
bg = "#171311"
fg = "#e6d5c2"
fg_dim = "#a09384"
comment = "#73665b"
cinder = "#d1766e"
ember = "#ea9875"
brass = "#fcba81"
sap = "#99af6b"
frost = "#4e89a2"
error = "#d25780"
warning = "#f4a21c"
ok = "#43b16a"
info = "#58bdff"

[directory]
truncate_to_repo = true

[kubernetes]
disabled = false
