# Plugins
set -g @plugin 'lloydbond/tmux-floating-terminal'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
run /usr/share/tmux-plugin-manager/tpm

# Session Persistence
set -g @continuum-restore 'on'

# Key Bindings
unbind r
bind r source-file ~/.config/tmux/tmux.conf

# Status Bar
set -g status-position top

