#!/usr/bin/env bash

# Define Extend the path
PATH=~/.local/bin:$PATH

# Define XDG Variables
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"
export XDG_CACHE_HOME="$HOME/.cache"

# Readline Configuration
export INPUTRC="$XDG_CONFIG_HOME/readline/inputrc"

# AWS Configuration
export AWS_SHARED_CREDENTIALS_FILE="$XDG_CONFIG_HOME/aws/credentials"
export AWS_CONFIG_FILE="$XDG_CONFIG_HOME/aws/config"

# Bash Configuration
export HISTFILE="${XDG_STATE_HOME}/bash/history"

