#!/usr/bin/env zsh

if command -v bat &>/dev/null; then
	alias cat='bat'
fi

alias df='df --human-readable'
alias k='kubectl'
alias less='less -R'
alias ll='ls --almost-all --human-readable --group-directories-first -l'
alias ls='ls -A --color=auto'
