#!/usr/bin/env zsh

fpath+="${HOME}/.local/share/zsh/site-functions/"

# Generate any missing completion scripts
_commands=(docker flux helm k9s kubectl pnpm)
for _command in ${_commands}; do
	_completion_path="${HOME}/.local/share/zsh/site-functions/_$_command";
	if command -v "$_command" >& /dev/null && [[ $(command -v "$_command") -nt "$_completion_path" ]]; then
		"$_command" completion zsh > "$_completion_path"
	fi
done

# Load completions
autoload -U compinit
compinit

# Configure completion behavior
zstyle ':completion:*' menu select
zstyle ':completion:*' matcher-list '' 'm:{a-zA-Z}={A-Za-z}'

